### ISSUE TITLE
Miniimagenet

### ISSUE THREAD

**Issue by wlaud1001** [mominabbass/Sharp-MAML#1]
Hi, I'm graduate student studying meta-learning and flat-minima.
I have seen your paper and would like to reproduce your results with miniimagenet.
Could you please release the code and script including miniimagenet and meta-test?

Thanks 
Best regards,
Jimyeong Kim

**Comment by mominabbass** [comment]
Hi Kim. Thanks for your question. For miniimagenet, we have added some comments in the files and also provided the settings in the main paper. We are currently in the process of finalizing the repo. Please allow us some time to do that.

**Comment by wlaud1001** [comment]
Thanks for the reply.
I posted the issue in a hurry. 
I look forward to the final version.
